spring.application.name=site

# These properties specify the data used for authentication and authroization for the database
# no spaces anywhere(inside brackets or outside)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#hardcoding the password fixed some things, therefore, the var env was set up wrongly

#this property is used to specify how we will handle data
spring.jpa.hibernate.ddl-auto=update

#logging only shows errors
spring.jpa.show-sql=false
logging.level.root=WARN
logging.level.com.restomgmt=INFO

#security configurations for user authentication, logging in, and role hierarchy
security.jwt.secret=${JWT_SECRET}

#react access to spring boot
app.cors.allowed-origins=${CORS_ALLOWED_ORIGIN}

#sessions - Redis for distributed sessions
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
